App_Login/urls.py
from django.urls import path
from . import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='sign_up'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('edit/', views.edit_profile, name='edit'),
    path('profile/', views.profile, name='profile'),
    path('user/<username>/', views.user, name='user'),
    path('follow/<username>/', views.follow, name='follow'),
    path('unfollow/<username>/', views.unfollow, name='unfollow')
]

App_Post/urls.py
from django.urls import path
from . import views

app_name = 'App_Post'

urlpatterns = [
    path('', views.home, name='home'),
    path('like/<pk>/', views.like, name='like'),
    path('unlike/<pk>/', views.unlike, name='unlike')
]

My_Social_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from App_Post import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('post/', include('App_Post.urls')),
    path('', views.home, name='home')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    description = models.TextField(blank=True)
    full_name = models.CharField(max_length=264, blank=True)
    dob = models.DateField(blank=True, null=True)
    website = models.URLField(blank=True)
    facebook = models.URLField(blank=True)

class Follow(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower')
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    created_date = models.DateTimeField(auto_now_add=True)

App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from  App_Login.models import UserProfile


class CreateNewUser(UserCreationForm):
    email = forms.EmailField(required=True, label="", widget=forms.TextInput(attrs={'placeholder': 'Enter Your email'}))
    username = forms.CharField(required=True, label="", widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password1 = forms.CharField(required=True, label="", widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(required=True, label="", widget=forms.PasswordInput(attrs={'placeholder': 'Password Confirmation'}))
    class Meta:
        model = User
        fields = ['email', 'username', 'password1', 'password2']


class EditProfile(forms.ModelForm):
    dob = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))
    class Meta:
        model = UserProfile
        exclude = ['user']

App_Login/views.py
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from App_Login.forms import CreateNewUser, EditProfile
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse, reverse_lazy
from App_Login.models import UserProfile, Follow
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required

from App_Post.forms import PostForm
from django.contrib.auth.models import User
# Create your views here.


def sign_up(request):
    form = CreateNewUser()
    registered = False
    if request.method == 'POST':
        form = CreateNewUser(data=request.POST)
        if form.is_valid():
            user = form.save()
            registered = True
            user_profile = UserProfile(user=user)
            user_profile.save()
            return HttpResponseRedirect(reverse('App_Login:login'))
    return render(request, 'App_Login/signup.html', context={'title': 'Sign Up . Instagram', 'form': form})


def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('App_Post:home'))
    return render(request, 'App_Login/login.html', context={'title': 'Login', 'form': form})


@login_required
def edit_profile(request):
    current_user = UserProfile.objects.get(user=request.user)
    form = EditProfile(instance=current_user)
    if request.method == 'POST':
        form = EditProfile(request.POST, request.FILES, instance=current_user)
        if form.is_valid():
            form.save()
            form = EditProfile(instance=current_user)
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/profile.html', context={'form': form, 'title': 'Edit Profile . Social'})


@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_Login:login'))


@login_required
def profile(request):
    current_user = request.user
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = current_user
            post.save()
            return HttpResponseRedirect(reverse('home'))
    return render(request, 'App_Login/user.html', context={'form': form})

@login_required
def user(request, username):
    user_other = User.objects.get(username=username)

    followed = False
    already_followed = Follow.objects.filter(follower=request.user, following=user_other)
    if already_followed:
        followed = True

    if user_other == request.user:
        return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/other_user.html', context={'user_other': user_other, 'followed': followed})

@login_required
def follow(request, username):
    follower_user = request.user
    following_user = User.objects.get(username=username)
    already_follow = Follow.objects.filter(follower=follower_user, following=following_user)
    if not already_follow:
        follow = Follow(follower=follower_user, following=following_user)
        follow.save()
    return HttpResponseRedirect(reverse('App_Login:user', kwargs={'username':username}))

@login_required
def unfollow(request, username):
    follower_user = request.user
    following_user = User.objects.get(username=username)
    already_follow = Follow.objects.filter(follower=follower_user, following=following_user)
    if already_follow:
        already_follow.delete()
    return HttpResponseRedirect(reverse('App_Login:user', kwargs={'username':username}))

templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}{{title}}{% endblock %}

{% block css_block %}
<style>
  .sign_up {
    width : 550px;
    margin: auto;
    border: 1px solid #ccc;
    padding: 30px;
  }
  .login{
    width: 550px;
    margin: auto;
    padding: 40px;
    border: 1px solid #ccc;
  }
</style>
{% endblock %}

{% block body_block %}

<div class="login">
  <form method="POST">
    {{form|crispy}}
    {% csrf_token %}

    <button type="submit" class='bnt btn-primary' style='width: 100%'>Login</button>
  </form>
</div>
<br>
<center>
<div class="sign_up">
  <p>Don't have an account? <a href="{% url 'App_Login:sign_up' %}">Sign up</a></p>
</div>
</center>
{% endblock %}

templates/App_Login/other_user.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %} user (@{{user_other.username}}) {% endblock %}
{% block css_block %}
<style>
  .crop{
    width: 230px;
    height: 260px;
    overflow: hidden;
    float: left;
  }
  .crop img{
    height: 260px;
    width: 230px;
    border: 1px solid #ddd;
    margin: 40px 5px 50px 0px;
    padding: 2px
    }
</style>
{% endblock %}
{% block body_block %}

<div class="row">
  <div class="col-sm-4">
    {% if user_other.user_profile.profile_pic %}
      <img src="/media/{{user_other.user_profile.profile_pic}}" width='250px' height='250px' class='rounded-circle'>
    {% else %}
      <img src='/media/default.jpg' width='250px' height='250px' class='rounded-circle'>
    {% endif %}
  </div>
  <div class="col-sm-8">
    <h3>{{user_other.username}}&nbsp;&nbsp;&nbsp
      {% if followed %}
      <a href="{% url 'App_Login:unfollow' username=user_other.username %}" style='text-decoration: none'>Unfollow</a>
      {% else %}
      <a href="{% url 'App_Login:follow' username=user_other.username %}" style='text-decoration: none'>Follow</a></h3>
      {% endif %}
    <h4>{{user_other.post.count}} post &nbsp; &nbsp; {{user_other.following.count}} follower &nbsp; &nbsp; {{user_other.follower.count}} following</h4>
    <br>
    <h4>{{user_other.user_profile.full_name}}</h4>
    <h6>{{user_other.user_profile.description|linebreaks}}</h6>
  </div>
</div><hr>

{% if user_other.post.count == 0 %}
<p class='alert alert-warning'>{{user_other.username}} didn't upload any photo before.</p>
{% else %}
<h3>{{user_other.username}}'s previous uploads</h3>
{% endif %}

{% for post in user_other.post.all %}
<div class="crop">
  <a href="/media/{{post.image}}"><img src="/media/{{post.image}}" title="{{post.caption}}"></a>
</div>
{% endfor %}

{% endblock %}

templates/App_Login/profile.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{title}} {% endblock %}

{% block css_block %}

{% endblock %}
{% block body_block %}
  <form method="POST" enctype='multipart/form-data'>
    {{form|crispy}}
    {% csrf_token %}

    <input type="submit" name="submit" value="Submit" class='btn btn-primary'>
  </form>

{% endblock %}

templates/App_Login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{title}} {% endblock %}
{% block css_block %}
<style>
  .sign_up {
    width : 550px;
    margin: auto;
    border: 1px solid #ccc;
    padding: 25px;
  }
  .login{
    width: 550px;
    padding: 30px;
    border: 1px solid #ccc
  }
</style>
{% endblock %}

{% block body_block %}
<div class="sign_up">
  <h3>Sign up to see photos from your friends.</h3><br>
  <form method="POST">
    {{form|crispy}}
    {% csrf_token %}

    <button type="submit" class='btn btn-primary' style='width: 100%'>Sign up</button>
  </form>
</div>
<br>
<center>
<div class="login">
  <p>Already have an account? <a href="{% url 'App_Login:login' %}">Login here</a></p>
</div>
</center>
{% endblock %}

templates/App_Login/user.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{user.user_profile.full_name}} (@{{user.username}}) {% endblock %}
{% block css_block %}
  <style>
    .crop{
      width: 230px;
      height: 260px;
      overflow: hidden;
      float: left;
    }
    .crop img{
      height: 260px;
      width: 230px;
      border: 1px solid #ddd;
      margin: 40px 5px 50px 0px;
      padding: 2px
      }
  </style>
{% endblock %}

{% block body_block %}
<div class="row">
  <div class="col-sm-4">
    {% if user.user_profile.profile_pic %}
      <img src="/media/{{user.user_profile.profile_pic}}" width='250px' height='250px' class='rounded-circle'>
    {% else %}
      <img src='/media/default.jpg' width='250px' height='250px' class='rounded-circle'>
    {% endif %}
  </div>
  <div class="col-sm-8">
    <h3>{{user.username}} &nbsp; <a href="{% url 'App_Login:edit'  %}" class='btn btn-light btn-sm'>Edit Profile</a></h3><br>
    <h4>{{user.post.count}} post &nbsp; &nbsp; {{user.following.count}} follower &nbsp; &nbsp; {{user.follower.count}} following</h4>
    <br>
    <h4>{{user.user_profile.full_name}}</h4>
    <h6>{{user.user_profile.description|linebreaks}}</h6>
  </div>
</div><hr>

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
  New Post
</button><br>
<div class="modal fade" id="myModal">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Post a Photo</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <form method="POST" enctype='multipart/form-data'>
          {{form|crispy}}
          {% csrf_token %}

          <button type="submit" class='btn btn-primary btn-sm'>Publish</button>
        </form>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div><br>
{% if user.post.count == 0 %}
<p class='alert alert-warning'>You didn't upload any photo before. Want to upload? <a href='' data-toggle="modal" data-target="#myModal">Upload</a></p>
{% else %}
<h3>Your previous uploads</h3>
{% endif %}

{% for post in user.post.all %}
<div class="crop">
  <a href="/media/{{post.image}}"><img src="/media/{{post.image}}" title="{{post.caption}}"></a>
</div>
{% endfor %}

<br><br><br>
{% endblock %}