App_Login/urls.py
from django.urls import path
from . import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='sign_up'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('edit/', views.edit_profile, name='edit'),
    path('profile/', views.profile, name='profile'),
    path('user/<username>/', views.user, name='user'),
    path('follow/<username>/', views.follow, name='follow'),
    path('unfollow/<username>/', views.unfollow, name='unfollow')
]

App_Post/urls.py
from django.urls import path
from . import views

app_name = 'App_Post'

urlpatterns = [
    path('', views.home, name='home'),
    path('like/<pk>/', views.like, name='like'),
    path('unlike/<pk>/', views.unlike, name='unlike')
]

My_Social_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from App_Post import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('post/', include('App_Post.urls')),
    path('', views.home, name='home')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Post/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post')
    image = models.ImageField(upload_to='post_images')
    caption = models.CharField(max_length=264)
    upload_date = models.DateTimeField(auto_now_add=True)
    upload_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-upload_date']
        
    def __str__(self):
        return self.caption

class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='liked_post')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liker')
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} : {self.post}'

App_Post/forms.py
from django import forms
from .models import Post,Like

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['caption','image']

App_Post/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from App_Post.models import Post,Like
from App_Login.models import Follow
# Create your views here.

@login_required
def home(request):
    dict = {}

    following_list = Follow.objects.filter(follower=request.user)
    posts = Post.objects.filter(author__in=following_list.values_list('following'))
    dict.update({'posts': posts})

    liked_post = Like.objects.filter(user=request.user)
    liked_post_list = liked_post.values_list('post', flat=True)
    dict.update({'liked_post_list': liked_post_list})

    if request.method == 'GET':
        search = request.GET.get('search')
        dict.update({'search': search})
        if search:
            result = User.objects.filter(username__icontains=search)
            dict.update({'result': result})
    dict.update({'title': 'Home'})
    return render(request, 'App_Post/home.html', context=dict)


@login_required
def like(request, pk):
    post = Post.objects.get(pk=pk)
    already_liked = Like.objects.filter(post=post, user=request.user)
    if not already_liked:
        like = Like(user=request.user, post=post)
        like.save()
    return HttpResponseRedirect(reverse('home'))

@login_required
def unlike(request, pk):
    post = Post.objects.get(pk=pk)
    already_liked = Like.objects.filter(post=post, user=request.user)
    if already_liked:
        already_liked.delete()
    return HttpResponseRedirect(reverse('home'))

templates/App_Post/home.html
{% extends 'navbar.html' %}
{% block title_block %} {{title}} {% endblock %}
{% block css_block %}

{% endblock %}

{% block body_block %}
{% if search %}
  {% for user in result %}

    <div class="row">
      <div class="col-sm-4">
        {% if user.user_profile.profile_pic %}
        <img src="/media/{{user.user_profile.profile_pic}}" alt="" width='60px' height='60px' class='rounded-circle'>
        {% else %}
        <img src="/media/default.jpg" alt="" width='60px' height='60px' class='rounded-circle'>
        {% endif %}
      </div>
      <div class="col-sm-8">
        <a href="{% url 'App_Login:user' username=user.username %}">{{user.username}}</a><br>
        {{user.user_profile.full_name}}
        <br>
      </div>
    </div>

  {% endfor %}
{% else %}

<marquee><h2 style='font-family: georgia'>All of the posts of your friends are appear here !</h2></marquee>
<br><br>


{% for post in posts %}
  <div class='row'>
    <div class="col-sm-8" style='border: 1px solid #ddd; padding:20px;'>
      {% if post.author.user_profile.profile_pic %}
        <img src="/media/{{post.author.user_profile.profile_pic}}" alt="UserPhoto" width='50px' height='50px' class='rounded-circle'>
      {% else %}
        <img src="/media/default.jpg" alt="" width='50px' height='50px' class='rounded-circle'>
      {% endif %}
      <a href="{% url 'App_Login:user' username=post.author %}">{{post.author}}</a>
      <h5>{{post.caption}}</h5>
      <img src="/media/{{post.image}}" alt="" width='100%'>

      <!-- love signs are here -->
      <div class="" style='padding: 20px'>
        {% if post.pk in liked_post_list %}
          <a href="{% url 'App_Post:unlike' pk=post.pk %}"><i class="fas fa-heart" style='font-size: 40px; float: left'></i></a>
        {% else %}
          <a href="{% url 'App_Post:like' pk=post.pk %}"><i class="far fa-heart" style='font-size: 40px; float: left'></i></a>
        {% endif %}

        <!-- Number of likes is here -->
        <p style='float: left; margin-left: 40px'> {{post.liked_post.count}} likes</p>
      </div>

    </div>
    <div class="col-sm-4">
      <div class="row" style='padding-left: 20px'>
        <div class="col-sm-4">
          {% if user.user_profile.profile_pic %}
          <img src="/media/{{user.user_profile.profile_pic}}" alt="" width='60px' height='60px' class='rounded-circle'>
          {% else %}
          <img src="/media/default.jpg" alt="" width='60px' height='60px' class='rounded-circle'>
          {% endif %}
        </div>
        <div class="col-sm-8">
          {{user.username}}<br>
          {{user.user_profile.full_name}}
        </div>
      </div>
    </div>
  </div>
  <br><br>
{% endfor %}

{% endif %}
{% endblock %}